import 'package:claycraft_google_gen_ai/models/user.dart';
import 'package:claycraft_google_gen_ai/models/product.dart';
import 'package:claycraft_google_gen_ai/models/order.dart';
import 'package:claycraft_google_gen_ai/models/design.dart';

class SampleData {
  // Pottery product images from Pixabay
  static const List<String> potteryImages = [
    'https://pixabay.com/get/g5ff84069e3e664c958ff4114c139fbe1480692bc080cedcf7b8bec1b18a1ef22772ab233c6966a4479fcea6e3804559d0be01142cf402e0a73c45eeeb4e15d75_1280.jpg',
    'https://pixabay.com/get/g0a685f0053ec1d1c9dd654fae9579fb11d61d4375c8129dfa63648004b9ed4b425798dcd69eadf01536b2b15be038e87fe8a6c40e64b957c27dd0eca5a0e4db8_1280.jpg',
    'https://pixabay.com/get/gc535760a9f7861a9144c2d6373c1260f45f55d6ce5ac008a167160ce4443e00ed40da5de1c867b81dca8c410866f5ff747eae7c763c92831e260ba7d3beb4b6a_1280.jpg',
    'https://pixabay.com/get/g3e801f78f36108ceda01e01360c5cab12ed67b5114fdae6880034d3be78bda57122a667f48b6a839444768c9a7e541f27451deff75900577659a2e95f43441dc_1280.jpg',
    'https://pixabay.com/get/gaf3025fbcc39e22746a3907e18ddfc44206a9eff02d1d3f033c4ec938a244258f69459ba0bdfc5d5d8e309b59c4e8a17a7a09e39932a9609b4e006eceb9d5e93_1280.jpg',
    'https://pixabay.com/get/g47f74b78d99a28e95b6f8419080a62518bb5cbf683fd7d566cf4c427e5a7a98976304b053183e15b69c8a4add5741266b719be99fc149836817002f8c7c800b1_1280.jpg',
    'https://pixabay.com/get/gda4a7440cb3c1ae4a18bbe74aedff29cbde6e460152fb924a0f2357aa1825268ebad95f151b6a8cc24732963668ad1cc45df55cfcef6722a28f4d481de5e366c_1280.jpg',
    'https://pixabay.com/get/g07a3a40944a28f46baa628d5ba2bcda7cb19ea965e11ca4b05f6f78a6378b208cdb7d1a08699156fa4089951ea8fbe702246cb55ba95331cb5cec08cbc866d23_1280.jpg',
  ];

  static List<User> getSampleArtisans() => [
    User(
      id: 'artisan_1',
      name: 'Elena Rodriguez',
      email: 'elena@claycraft.com',
      role: UserRole.artisan,
      bio: 'Master potter specializing in traditional Mexican ceramics with 15 years of experience.',
      location: 'Oaxaca, Mexico',
      profileImage: potteryImages[6],
      createdAt: DateTime.now().subtract(const Duration(days: 365)),
      specialty: 'Traditional Mexican Pottery',
      yearsExperience: 15,
      skills: ['Hand-throwing', 'Glazing', 'Traditional firing'],
      rating: 4.8,
    ),
    User(
      id: 'artisan_2',
      name: 'Kenji Tanaka',
      email: 'kenji@claycraft.com',
      role: UserRole.artisan,
      bio: 'Contemporary ceramic artist focusing on minimalist Japanese-inspired designs.',
      location: 'Kyoto, Japan',
      profileImage: potteryImages[7],
      createdAt: DateTime.now().subtract(const Duration(days: 200)),
      specialty: 'Minimalist Ceramics',
      yearsExperience: 8,
      skills: ['Wheel throwing', 'Raku firing', 'Modern glazing'],
      rating: 4.9,
    ),
    User(
      id: 'artisan_3',
      name: 'Sarah Thompson',
      email: 'sarah@claycraft.com',
      role: UserRole.artisan,
      bio: 'Rustic pottery maker creating functional pieces with earthy, natural finishes.',
      location: 'Vermont, USA',
      profileImage: potteryImages[6],
      createdAt: DateTime.now().subtract(const Duration(days: 500)),
      specialty: 'Rustic Functional Pottery',
      yearsExperience: 12,
      skills: ['Stoneware', 'Wood firing', 'Natural glazes'],
      rating: 4.7,
    ),
  ];

  static List<User> getSampleBuyers() => [
    User(
      id: 'buyer_1',
      name: 'Michael Chen',
      email: 'michael@email.com',
      role: UserRole.buyer,
      bio: 'Pottery enthusiast and collector',
      location: 'San Francisco, USA',
      createdAt: DateTime.now().subtract(const Duration(days: 100)),
      interests: ['Traditional pottery', 'Home decor'],
      favoriteStyles: ['traditional', 'minimalist'],
    ),
  ];

  static List<Product> getSampleProducts() => [
    Product(
      id: 'prod_1',
      name: 'Handcrafted Ceramic Bowl',
      description: 'Beautiful handcrafted ceramic bowl perfect for serving or decoration. Made with traditional techniques passed down through generations.',
      price: 45.0,
      category: ProductCategory.bowl,
      style: ProductStyle.traditional,
      images: [potteryImages[0]],
      artisanId: 'artisan_1',
      artisanName: 'Elena Rodriguez',
      estimatedDays: 7,
      materials: ['Clay', 'Natural glazes'],
      dimensions: {'diameter': '8 inches', 'height': '3 inches'},
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      rating: 4.8,
      reviewCount: 12,
      isCustomizable: true,
    ),
    Product(
      id: 'prod_2',
      name: 'Minimalist Ceramic Vase',
      description: 'Clean-lined ceramic vase with a contemporary aesthetic. Perfect for modern homes and floral arrangements.',
      price: 75.0,
      category: ProductCategory.vase,
      style: ProductStyle.minimalist,
      images: [potteryImages[1]],
      artisanId: 'artisan_2',
      artisanName: 'Kenji Tanaka',
      estimatedDays: 10,
      materials: ['Porcelain', 'Matte glaze'],
      dimensions: {'diameter': '4 inches', 'height': '10 inches'},
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      rating: 4.9,
      reviewCount: 8,
      isCustomizable: false,
    ),
    Product(
      id: 'prod_3',
      name: 'Rustic Dinner Plate',
      description: 'Handmade stoneware dinner plate with natural earth tones. Microwave and dishwasher safe.',
      price: 28.0,
      category: ProductCategory.plate,
      style: ProductStyle.rustic,
      images: [potteryImages[2]],
      artisanId: 'artisan_3',
      artisanName: 'Sarah Thompson',
      estimatedDays: 5,
      materials: ['Stoneware', 'Natural finish'],
      dimensions: {'diameter': '10 inches', 'thickness': '0.5 inches'},
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      rating: 4.6,
      reviewCount: 15,
      isCustomizable: true,
    ),
    Product(
      id: 'prod_4',
      name: 'Artisan Coffee Mug',
      description: 'Perfect morning companion. This handcrafted mug features a comfortable handle and beautiful glazed finish.',
      price: 32.0,
      category: ProductCategory.mug,
      style: ProductStyle.contemporary,
      images: [potteryImages[3]],
      artisanId: 'artisan_1',
      artisanName: 'Elena Rodriguez',
      estimatedDays: 6,
      materials: ['Ceramic', 'Food-safe glaze'],
      dimensions: {'diameter': '4 inches', 'height': '4 inches', 'capacity': '12 oz'},
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      rating: 4.7,
      reviewCount: 20,
      isCustomizable: true,
    ),
    Product(
      id: 'prod_5',
      name: 'Abstract Ceramic Sculpture',
      description: 'Unique abstract sculpture that brings artistic flair to any space. Each piece is one-of-a-kind.',
      price: 120.0,
      category: ProductCategory.sculpture,
      style: ProductStyle.modern,
      images: [potteryImages[4]],
      artisanId: 'artisan_2',
      artisanName: 'Kenji Tanaka',
      estimatedDays: 14,
      materials: ['High-fire clay', 'Crystalline glaze'],
      dimensions: {'height': '8 inches', 'width': '6 inches'},
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      rating: 5.0,
      reviewCount: 5,
      isCustomizable: false,
    ),
    Product(
      id: 'prod_6',
      name: 'Decorative Pottery Set',
      description: 'Elegant set of three decorative pottery pieces. Perfect for home styling and gift-giving.',
      price: 85.0,
      category: ProductCategory.decorative,
      style: ProductStyle.contemporary,
      images: [potteryImages[5]],
      artisanId: 'artisan_3',
      artisanName: 'Sarah Thompson',
      estimatedDays: 12,
      materials: ['Terracotta', 'Metallic accents'],
      dimensions: {'set': '3 pieces', 'largest': '6 inches tall'},
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      rating: 4.8,
      reviewCount: 7,
      isCustomizable: true,
    ),
  ];

  static List<Order> getSampleOrders() => [
    Order(
      id: 'order_1',
      productId: 'prod_1',
      productName: 'Handcrafted Ceramic Bowl',
      buyerId: 'buyer_1',
      artisanId: 'artisan_1',
      totalPrice: 45.0,
      status: OrderStatus.inProgress,
      orderDate: DateTime.now().subtract(const Duration(days: 3)),
      estimatedCompletion: DateTime.now().add(const Duration(days: 4)),
      customRequirements: 'Please add blue accents to match kitchen decor',
      shippingAddress: '123 Main St, San Francisco, CA 94102',
    ),
  ];

  static List<Design> getSampleDesigns() => [
    Design(
      id: 'design_1',
      name: 'Modern Fruit Bowl',
      userId: 'buyer_1',
      description: 'Contemporary fruit bowl with clean lines and smooth finish',
      specifications: {
        'shape': 'circular',
        'size': 'medium',
        'style': 'modern',
        'color': 'white with blue rim',
        'capacity': 'holds 6-8 fruits'
      },
      suggestedArtisans: ['artisan_2', 'artisan_3'],
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      isPublic: true,
      inspirationSource: 'Scandinavian design',
    ),
  ];

  // Community discussion topics
  static List<Map<String, dynamic>> getCommunityTopics() => [
    {
      'id': 'topic_1',
      'title': 'Traditional vs Modern Pottery Techniques',
      'author': 'Elena Rodriguez',
      'authorRole': 'Artisan',
      'replies': 23,
      'lastActivity': DateTime.now().subtract(const Duration(hours: 2)),
      'category': 'Techniques',
      'description': 'Discussing the benefits of traditional hand-throwing vs modern pottery wheels...'
    },
    {
      'id': 'topic_2',
      'title': 'Best Glazes for Food-Safe Pottery',
      'author': 'Sarah Thompson',
      'authorRole': 'Artisan',
      'replies': 15,
      'lastActivity': DateTime.now().subtract(const Duration(hours: 6)),
      'category': 'Materials',
      'description': 'Sharing experiences with different food-safe glazes and their applications...'
    },
    {
      'id': 'topic_3',
      'title': 'Caring for Your Handmade Pottery',
      'author': 'Michael Chen',
      'authorRole': 'Buyer',
      'replies': 8,
      'lastActivity': DateTime.now().subtract(const Duration(days: 1)),
      'category': 'Care & Maintenance',
      'description': 'Tips for maintaining and cleaning handcrafted pottery pieces...'
    },
  ];
}